### ISSUE TITLE
Device ID

### ISSUE THREAD

**Issue by Th3AL0** [NishanthKabra/Ionic2-PushNotifications#1]
Nice Repo!

But, i'm having a question about:

```
 //Take the registration id(lengthy string) that you logged 
    //in your ionic v2 app and update device_tokens[0] with it for testing.
```

**Where do i exactly can find the device id's ? This is my log after ionic serve c**

> 836090   warn     Native: tried calling StatusBar.styleDefault, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
> 2     836092   warn     Native: tried calling Push.init, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
> 3     836106   group    EXCEPTION: Error: Uncaught (in promise): TypeError: push.on is not a function
> 5     836108   error    STACKTRACE:
> 4     836107   error    EXCEPTION: Error: Uncaught (in promise): TypeError: push.on is not a function
> 6     836109   error    Error: Uncaught (in promise): TypeError: push.on is not a function
>     at resolvePromise (http://localhost:8100/build/js/angular2-polyfills.js:602:32)
>     at http://localhost:8100/build/js/angular2-polyfills.js:638:18
>     at ZoneDelegate.invokeTask (http://localhost:8100/build/js/angular2-polyfills.js:423:38)
>     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (http://localhost:8100/build/js/app.bundle.js:27193:41)
>     at ZoneDelegate.invokeTask (http://localhost:8100/build/js/angular2-polyfills.js:422:43)
>     at Zone.runTask (http://localhost:8100/build/js/angular2-polyfills.js:320:48)
>     at drainMicroTaskQueue (http://localhost:8100/build/js/angular2-polyfills.js:541:36)
>     at HTMLDocument.ZoneTask.invoke (http://localhost:8100/build/js/angular2-polyfills.js:493:22)
> 7     836110   groupEnd
> 8     836112   error    Unhandled Promise rejection:, push.on is not a function, ; Zone:, angular, ; Task:, Promise.then, ; Value:, [object Object]

**Comment by NishanthKabra** [comment]
Hey @AlexandreLogist, i think there are some issues when you are pushing this code to your android device. It will be better if you create a blank side menu ionic2 project and deploy it to push without any errors.(This tutorial was specifically meant for ionic 2 typescript side menu template).
There are 2 things i would like you to confirm.
1. Did you add push plugin in your project?
cordova plugin add phonegap-plugin-push --variable SENDER_ID="XXXXXXXXX"
2.Did you import Push from ionic-native?
import {Push} from 'ionic-native';
3. YOU WILL BE GETTING DEVICE IDS ONLY ON REAL DEVICE.(NOT ON SIMULATOR OR BROWSER).
4. If you are doing ionic serve, its expected to give errors.
5. PLease try on it on a android device and let me know if you still face issues.
![push_issue1](https://cloud.githubusercontent.com/assets/5277668/15495259/81eea660-21ac-11e6-97b4-461ef8edeb1a.PNG)
1. The highlighted portion in the attached image is my device Id. 
2. If you have any difficulties we can catch up and fix it.

**Comment by NishanthKabra** [comment]
I assume the issue has been resolved for you, So closing this issue.
